export const accidentConstants = {
   GET_DATA_ACCIDENT: 'GET_DATA_ACCIDENT',
   GET_DATA_ACCIDENT_RATE: 'GET_DATA_ACCIDENT_RATE',
   GET_DATA_LAST_ACCIDENT: 'GET_DATA_LAST_ACCIDENT',
   GET_ACCIDENT_OPTION: 'GET_ACCIDENT_OPTION',
   GET_DATA_FILTER_ACCIDENT: 'GET_DATA_FILTER_ACCIDENT',
   GET_DATA_REPORT_ACCIDENT: 'GET_DATA_REPORT_ACCIDENT',
}