export const dashboardConstant = {
  STORE_DAILY_TRANSACTION: 'STORE_DAILY_TRANSACTION',
  STORE_DAILY_TRAFFIC: 'STORE_DAILY_TRAFFIC',
  STORE_MONTHLY_TRANSACTION: 'STORE_MONTHLY_TRANSACTION',
  STORE_MONTHLY_TRAFFIC: 'STORE_MONTHLY_TRAFFIC',
  STORE_PERCENTAGE_TRANSACTION_TRAFFIC: 'STORE_PERCENTAGE_TRANSACTION_TRAFFIC',
  STORE_TRANSACTION_TRAFFIC_BY_REALISASI: 'STORE_TRANSACTION_TRAFFIC_BY_REALISASI',
  STORE_TRANSACTION_TRAFFIC_MONTHLY_BY_REALISASI: 'STORE_TRANSACTION_TRAFFIC_MONTHLY_BY_REALISASI',
  STORE_COMPARISON_TRANSACTION_TRAFFIC_MONTHLY_BY_REALISASI: 'STORE_COMPARISON_TRANSACTION_TRAFFIC_MONTHLY_BY_REALISASI',
  STORE_BANK_TRANSACTION: 'STORE_BANK_TRANSACTION'
}