export const senkomConstants = {
   DEFAULT: 'DEFAULT',
   GET_ALL_DATA_SENKOM: 'GET_ALL_DATA_SENKOM',
   GET_DATA_SENKOM_BY_ID: 'GET_DATA_SENKOM_BY_ID',
   GET_DATA_FILTER_SENKOM: 'GET_DATA_FILTER_SENKOM',
   GET_EXCEL_SENKOM:'GET_EXCEL_SENKOM'
}