export const settlementConstant = {
  STORE_DAILY_SETTLEMENT:'STORE_DAILY_SETTLEMENT',
  STORE_MONTHLY_SETTLEMENT:'STORE_MONTHLY_SETTLEMENT',
  STORE_REKENING_KORAN:'STORE_REKENING_KORAN',
  STORE_REKENING_BAGI_HASIL:'STORE_REKENING_BAGI_HASIL'
}