export const userConstants = {
   LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
   LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
   LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
   LOGOUT: 'LOGOUT',
   INTERNALSERVERERROR: 'INTERNALSERVERERROR',
   USER_STORE_IDENTITY: 'USER_STORE_IDENTITY',
   GET_ALL_USER: 'GET_ALL_USER',
   PASSWORD_CORRECTION: 'PASSWORD_CORRECTION',
   GET_USER_ACTION: 'GET_USER_ACTION'
}